# Generated by Django 4.0.5 on 2022-06-26 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=2, verbose_name='Код страны')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=10, verbose_name='Код региона')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=10, unique=True, verbose_name='Идентификатор')),
                ('local_code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('elevation_ft', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_code', models.CharField(blank=True, max_length=255, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=10, null=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport', to='avia.continent', verbose_name='Континент')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport', to='avia.country', verbose_name='Страна')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport', to='avia.municipality', verbose_name='Город')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport', to='avia.region', verbose_name='Регион')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport', to='avia.airporttype', verbose_name='Тип аэропорта')),
            ],
        ),
    ]
