# Generated by Django 4.0.5 on 2022-06-27 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avia', '0002_alter_airport_options_alter_airporttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('comment', models.CharField(max_length=255, verbose_name='Наименование')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                              to='avia.airport', verbose_name='аэропорт')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='comments', to=settings.AUTH_USER_MODEL,
                                           verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
