# Generated by Django 4.0.5 on 2022-06-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avia', '0004_alter_airport_continent_alter_airport_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='local_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код'),
        ),
    ]
