name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.10"
    - name: Change app working dir
      run: |
        cd app
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:${{github.sha}}-$(date +%s)
