name: Django CI

on:
  pull_request:
    branches: [ "master" ]

env:
  POSTGRES_DB: "db-udw-avia-dev" 
  POSTGRES_USER: "udw-avia-dev"
  POSTGRES_PASSWORD: ${{ secrets.PostgresDevPass }} 

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
#    - name: Set up Python 3.8.10
#      uses: actions/setup-python@v3
#      with:
#        python-version: "3.8.10"
#    - name: Install Dependencies
#      working-directory: ./app
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#    - name: Run Tests
#      working-directory: ./app
#      run: |
#        python manage.py test
    - name: "build docker container"
      run: |
        echo "POSTGRES_DB=udw-avia-dev" >> app/.env
        echo "POSTGRES_USER=udw-avia-dev" >> app/.env
        echo "POSTGRES_PASSWORD=${{ secrets.PostgresDevPass }}" >> app/.env
        docker-compose build
        docker-compose up -d db
    - name: Execute tests in container
      run: |
        docker run -it backend_web  python3 manage.py test
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to stage
      run: |
        echo "POSTGRES_DB=udw-avia-dev" >> app/.env
        echo "POSTGRES_USER=udw-avia-dev" >> app/.env
        echo "POSTGRES_PASSWORD=${{ secrets.PostgresDevPass }}" >> app/.env
        docker-compose build
        docker-compose up -d

